/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.mmec.business.bean;

import java.io.Serializable;

public class Cert3Info implements Serializable {

	private static final long serialVersionUID = 1L;

	public int userId; // required
	public String serial_number; // required
	public String cert_content; // required
	public String subject_item; // required
	public String begintime; // required
	public String endtime; // required
	public String cer_type; // required
	public String signature; // required
	public String encrypt_data; // required
	public String data; // required

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getSerial_number() {
		return serial_number;
	}

	public void setSerial_number(String serial_number) {
		this.serial_number = serial_number;
	}

	public String getCert_content() {
		return cert_content;
	}

	public void setCert_content(String cert_content) {
		this.cert_content = cert_content;
	}

	public String getSubject_item() {
		return subject_item;
	}

	public void setSubject_item(String subject_item) {
		this.subject_item = subject_item;
	}

	public String getBegintime() {
		return begintime;
	}

	public void setBegintime(String begintime) {
		this.begintime = begintime;
	}

	public String getEndtime() {
		return endtime;
	}

	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	public String getCer_type() {
		return cer_type;
	}

	public void setCer_type(String cer_type) {
		this.cer_type = cer_type;
	}

	public String getSignature() {
		return signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public String getEncrypt_data() {
		return encrypt_data;
	}

	public void setEncrypt_data(String encrypt_data) {
		this.encrypt_data = encrypt_data;
	}

	public String getData() {
		return data;
	}

	public void setData(String data) {
		this.data = data;
	}

}
